### PR TITLE
Goalie Challenge

### PR DESCRIPTION
**Pull request by nunolau**
Goalie Challenge is implemented as a new option to be used for RoboCup 2018
ServerController is not used to start the server because it was not always starting it, the server is started through a bash script executed in Java

### CODE REVIEW

**Comment by Gama11** [comment]
Hm, that server issue sounds strange, I guess that's fine as a short-term workaround for now, but eventually we need to figure out why it's not working properly.

Could the readme be updated with a section about the goalie challenge section, explaining the rules etc (similar to what we have for the other challenges)?

Also, what's `kicks.py` for, just something for testing I guess?

**Comment by nunolau** [comment]
Hi Jens,

I agree with you that it is strange. I just sent a message to klaus with a more complete explanation:

The delay between attempts also appears in our tests, but not as big as 5 minutes, anyway it seemed to get bigger and bigger as the runs went on. This is quite strange as this problem also appears in the kick challenge, and probably also the others, using a clean clone from you repository. We also think the introduction of the goalie challenge did not change anything related to the management of server starting, agent starting and sockets.
Anyway, we debugged the problem and it seems that server.startServer(0) in BenchmarkMain.java is not always starting the  server, creating these delays. If we do not use the ServerController and execute a bash script from Java, being the start script responsible for starting the server, the problem does not appear in our tests. The solution is not optimal, as now the ServerController is instantiated but almost not used...

Yes, we will also update the readme.

kicks.py was used to set the initial contents of kicks.csv (that contains the list of all possible kicks), but it is not an essential tool now.

Cheers,
Nuno

________________________________

**Comment by nunolau** [comment]
updated README.md for goalie challenge

**Comment by Gama11** [comment]
The readme additions look good! Thanks for taking the time to make a pull request.

Fixed a few code style issues before merging. I will also tag a 2.7 release of magmaChallenge.

**Pull request merged**
